name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/mateszadam/test:0.1
        docker login ghcr.io -u mateszadam -p ${{secrets.GHCL_TOKEN}}
        docker push ghcr.io/mateszadam/test:0.1
