name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "html/**"
  pull_request:
    branches: ["main"]
    paths:
      - "html/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          cd html

          docker build . --file Dockerfile --tag ghcr.io/mateszadam/web_test_for_azure:$IMAGE_TAG
          docker login ghcr.io -u mateszadam -p ${{secrets.GHCL_TOKEN}}
          docker push ghcr.io/mateszadam/test:0.1
