# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TEST-13A

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9709bd8d46c44edcae4d95d28d6e4dfe }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7b739ff00ca64d9bb03c32f0a775a916 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_9709bd8d46c44edcae4d95d28d6e4dfe }}/mateszadam/web_test_for_azure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TEST-13A'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0b9e326338f48f6a0cb8f3f48b9b0ae }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_9709bd8d46c44edcae4d95d28d6e4dfe }}/mateszadam/web_test_for_azure:${{ github.sha }}'